# Application Name
spring.application.name=myPortfolio-1

# --- SERVER PORT CONFIGURATION ---
server.port=${PORT:8080}

# --- DATABASE CONFIGURATION ---
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# Local Database (Jab aap PC par test karein)
#spring.datasource.url=jdbc:mysql://localhost:3306/portfolio
#spring.datasource.username=root
#spring.datasource.password=golu@111

# Cloud Database (Clever Cloud ke liye, jab Render par push karein toh inko uncomment kar lein)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate Settings ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- Thymeleaf Settings ---
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# --- File Upload Configuration ---
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

# ==========================================
# --- BREVO EMAIL API CONFIGURATION ---
# ==========================================
# Yahan apni generate ki hui 64-character wali Standard Key paste karein
brevo.api.key=${API_KEY}