# Application Name
spring.application.name=myPortfolio-1

# --- ONLINE DATABASE CONFIGURATION (Clever Cloud) ---
# Yahan apni Clever Cloud se aayi details dalein
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate Settings ---
# Online database ke liye 'update' rakha hai taaki tables ban jayein, aur show-sql 'false' kiya hai taaki console clean rahe
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# --- Thymeleaf ki default settings ---
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# --- File Upload Configuration (Aditya's Optimized Settings) ---
# 1MB set kiya gaya hai server aur network bachane ke liye
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB