# Application Name
spring.application.name=myPortfolio-1

# --- ONLINE DATABASE CONFIGURATION (Clever Cloud) ---
# Render ke variables se match karne ke liye change kiya gaya hai
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate Settings ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Ye line add karna zaroori hai Dialect error fix karne ke liye
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- Thymeleaf ki default settings ---
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# --- File Upload Configuration ---
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB